### ISSUE TITLE
what is dataset about Oil-Portrait ⟷ Photography I need

### ISSUE THREAD

**Issue by Johnson-yue** [CompVis/net2net#1]
thank you for shareing your code and pretrained model.

If I want to retrain the unpaired - traslation task  Oil-Portrait ⟷ Photography  what is dataset I need ?

such as , how many Oil portrait images?   and how many real human image photograph? 

I want to train a pretrained model by myself, thank you

**Comment by rromb** [comment]
**Oil-Portrait** ⟷ **Photography**:  The training config is `configs/creativity/portraits_photography_256.yaml`
You first have to download the autoencoder checkpoint ([Download Portrait+Photography](https://heibox.uni-heidelberg.de/f/4f9449418a2e4025bb5f/)) and then place it into `logs/2020-09-29T23-47-10_PortraitsAndFFHQ/checkpoints/epoch=000004.ckpt`. The dataset can be downloaded [here](https://heibox.uni-heidelberg.de/f/4f35bdc16eea4158aa47/?dl=1).

The size of the oil-portrait dataset is 16298 images for the train split and 1810 images for the validation split. The real photos are simply the images from the FFHQ dataset (70000 images in total).
